/**
 * Focused measurement + correctness check for Session 3.9's exercise-catalog
 * delta-sync (and the 1000-row-cap paging fix).
 *
 *   npx tsx scripts/perf-catalog-delta.ts
 *
 * Read-only. Two jobs:
 *  1. CORRECTNESS — page the full catalog through getExerciseCatalogDelta and
 *     assert it matches COUNT(*) exactly, with no duplicate ids and a strictly
 *     monotonic (updated_at, id) order. This is the empirical proof the internal
 *     keyset paging neither skips nor repeats rows across the PostgREST 1000-cap.
 *  2. PAYLOAD — compare, in deterministic bytes (not noisy wall-clock):
 *       OLD full   — getExercisesForCoach (all columns)
 *       NEW lean   — getExerciseCatalogDelta(coach)            (first sync, 5 cols)
 *       NEW delta  — getExerciseCatalogDelta(coach, recentTs)  (steady state)
 *
 * Measured snapshot (2026-05-29, scale fixture, target aeaphsslctwcmebldrzx):
 *   catalog COUNT(*) = 1512 (global + coach)
 *   - full sync paged across 2 pages, returned all 1512 rows (no dups, monotonic)
 *     -> the pre-fix single query capped at 1000, silently dropping 512 rows
 *   - lean 168.7 B/row vs fat 290.2 B/row  -> 41.9% smaller (sparse fieldset)
 *   - steady-state delta: 0 rows / 2 bytes vs a 254,999-byte full re-download
 * (perf-baseline.md is auto-generated by perf-baseline.ts, so it would clobber a
 *  hand-added section — this script is the durable, reproducible record.)
 */
import "./env-bootstrap";

import { supabaseAdmin } from "@/services/supabase-admin";
import {
  getExercisesForCoach,
  getExerciseCatalogDelta,
  type ExerciseCatalogDeltaRow,
} from "@/services/exercise-catalog-service";
import { PERF_CLIENT_ID } from "./perf-fixtures";

function bytes(x: unknown): number {
  return Buffer.byteLength(JSON.stringify(x), "utf8");
}

function perRow(totalBytes: number, rows: number): string {
  return rows > 0 ? (totalBytes / rows).toFixed(1) : "n/a";
}

function assertComplete(rows: ExerciseCatalogDeltaRow[], expectedCount: number): void {
  if (rows.length !== expectedCount) {
    throw new Error(`paging returned ${rows.length} rows, expected COUNT(*) = ${expectedCount}`);
  }
  const ids = new Set(rows.map((r) => r.id));
  if (ids.size !== rows.length) {
    throw new Error(`paging returned ${rows.length - ids.size} duplicate id(s)`);
  }
  for (let i = 1; i < rows.length; i++) {
    const a = rows[i - 1];
    const b = rows[i];
    const ordered = a.updated_at < b.updated_at || (a.updated_at === b.updated_at && a.id < b.id);
    if (!ordered) {
      throw new Error(`order violation at index ${i}: (${a.updated_at}, ${a.id}) !< (${b.updated_at}, ${b.id})`);
    }
  }
}

async function main() {
  await supabaseAdmin.from("clients").select("id").limit(1); // prime the pool

  const { data: client, error } = await supabaseAdmin
    .from("clients")
    .select("coach_id")
    .eq("id", PERF_CLIENT_ID)
    .single();
  if (error || !client?.coach_id) {
    throw new Error(`perf client coach not found: ${error?.message ?? "no coach_id"}`);
  }
  const coachId = client.coach_id;

  // True size of the visible catalog (server-side COUNT, immune to the row cap).
  const { count, error: countErr } = await supabaseAdmin
    .from("exercises")
    .select("id", { count: "exact", head: true })
    .or(`coach_id.eq.${coachId},coach_id.is.null`);
  if (countErr) throw new Error(`count failed: ${countErr.message}`);
  const trueCount = count ?? 0;

  console.log(`perf client: ${PERF_CLIENT_ID}`);
  console.log(`coach:       ${coachId}`);
  console.log(`catalog COUNT(*) (global + coach): ${trueCount}\n`);

  const leanFull = await getExerciseCatalogDelta(coachId);
  assertComplete(leanFull, trueCount);
  console.log(`✓ paging correctness: full sync returned all ${leanFull.length} rows, no dups, monotonic (updated_at, id)`);
  console.log(`  ${trueCount > 1000 ? `(paged past the 1000-row cap — ${Math.ceil(trueCount / 1000)} pages)` : "(single page — under the 1000 cap)"}\n`);

  const fat = await getExercisesForCoach(coachId);
  const sinceRecent = new Date(Date.now() - 60_000).toISOString();
  const delta = await getExerciseCatalogDelta(coachId, sinceRecent);

  const fatRows = Array.isArray(fat) ? fat.length : 0;
  const fatB = bytes(fat);
  const leanB = bytes(leanFull);
  const deltaB = bytes(delta);

  console.log("=== Payloads (deterministic: rows + serialized JSON bytes) ===\n");
  console.log(`OLD  full catalog (getExercisesForCoach, all columns) : rows=${fatRows}  bytes=${fatB}  (${perRow(fatB, fatRows)} B/row)`);
  console.log(`NEW  full lean    (catalog delta, no since, 5 columns) : rows=${leanFull.length}  bytes=${leanB}  (${perRow(leanB, leanFull.length)} B/row)`);
  console.log(`NEW  delta        (since 60s ago, steady state)        : rows=${delta.length}  bytes=${deltaB}`);
  console.log("");
  const fatPerRow = fatRows ? fatB / fatRows : 0;
  const leanPerRow = leanFull.length ? leanB / leanFull.length : 0;
  console.log(`Lean vs fat per row : ${((1 - leanPerRow / fatPerRow) * 100).toFixed(1)}% fewer bytes/row (sparse fieldset)`);
  console.log(`Steady-state delta  : ${deltaB} bytes vs a ${leanB}-byte full re-download (delta-sync win)`);
}

main().catch((err) => {
  console.error("catalog-delta measurement failed:", err);
  process.exit(1);
});
