-- =============================================================================
-- Migration 189: an exercise done with bodyweight alone is Bodyweight
-- (docs/TRAINING-UPGRADE-EXECUTION-PLAN.md §4.4, amended by the owner 2026-09-21)
--
-- Migration 185 made every global compound and isolation exercise Strength by
-- rule without reading its equipment, so 225 exercises done with bodyweight
-- alone — Pull Up, Push Up, Dip, Pistol Squat, Burpee — started on Strength's
-- columns, Load included, and charted by weight first. The owner's split of
-- the 225:
--   - 199 are Bodyweight: their preset asks for reps, RPE and rest, and their
--     chart leads with the best set's reps;
--   - the 15 static stretches are Holds: held for time;
--   - the 11 "Weighted" variants stay Strength: the load is part of the
--     prescription.
--
-- Coach-made rows keep their type (the coach sets it in the exercise form).
-- These lists, applied after migration 185's, give the Type column of
-- scripts/data/exercises.csv row for row: utils/exercise-types.test.ts applies
-- every migration's lists in order and compares the result with the CSV.
-- PROD's catalog is empty, so there the seed writes these types.
--
-- Re-runnable: each update sets a type by name.
-- =============================================================================

UPDATE public.exercises SET exercise_type = 'bodyweight'
WHERE coach_id IS NULL AND lower(name) = ANY (ARRAY[
  'ab bicycle',
  'alternating v-up',
  'archer pull up',
  'archer push up',
  'atg lunge',
  'bear crawl',
  'bear crawl to push up',
  'behind neck pull up',
  'bicycle crunch',
  'bicycle v-up',
  'bird dog',
  'bird dog to push up',
  'body saw plank',
  'bodyweight calf raise',
  'bodyweight dip narrow grip',
  'bodyweight hip thrust single leg elevated',
  'bodyweight squat',
  'bodyweight tricep extension',
  'box pistol squat',
  'box step up',
  'burpee',
  'burpee pull up',
  'cat cow',
  'chin up',
  'cindy wod',
  'close grip chin up',
  'close grip pull up',
  'close grip push up on bench',
  'commando pull up',
  'copenhagen plank raise',
  'cossack squat',
  'crab walk',
  'crawl',
  'cross body mountain climber',
  'crunch',
  'curtsy lunge to lateral lunge',
  'dead bug',
  'dead bug march',
  'decline bench leg raise',
  'decline crunch',
  'decline push up',
  'decline reverse crunch',
  'deficit push up',
  'diamond push up',
  'dip',
  'donkey kick',
  'dragon flag',
  'dragon flag negative',
  'eccentric calf raise',
  'eccentric chin up',
  'eccentric hamstring slide',
  'eccentric nordic curl',
  'eccentric pull up',
  'eccentric push up',
  'elephant walk',
  'elevated heel squat bodyweight',
  'emom burpees',
  'fire hydrant',
  'flutter kick',
  'frog pump',
  'front lever row',
  'glute bridge',
  'glute bridge march',
  'glute focused back extension',
  'glute ham raise',
  'handstand push up',
  'handstand walk',
  'hanging garhammer raise',
  'hanging knee raise',
  'hanging leg raise',
  'hanging oblique knee raise',
  'hanging windshield wiper',
  'hanging windshield wiper straight leg',
  'heel touch',
  'high box step up',
  'hindu push up',
  'hip 90/90 switch',
  'hip airplane',
  'hollow body flutter kick',
  'hollow body rock',
  'hyperextension',
  'hyperextension with rotation',
  'inchworm',
  'inchworm to push up',
  'incline bench reverse crunch',
  'incline push up',
  'inverted row',
  'kot squat',
  'l-sit pull up',
  'lateral lunge to balance',
  'lateral squat',
  'leg raise',
  'lunge',
  'lying side crunch',
  'mixed grip pull up',
  'mountain climber',
  'murph wod',
  'muscle up',
  'natural glute ham raise',
  'neutral grip pull up',
  'nordic hamstring curl',
  'oblique crunch',
  'overhead squat bodyweight',
  'parallette push up',
  'pause dip',
  'peterson step down',
  'pike push up',
  'pike walk out',
  'pistol squat',
  'planche lean',
  'plank to downward dog',
  'plank to push up',
  'plank to side plank',
  'plank with shoulder tap',
  'prisoner squat',
  'pull up',
  'push up',
  'quadruped hip circle',
  'quadruped rock back',
  'razor curl',
  'rear foot elevated hip thrust',
  'reverse crunch',
  'reverse crunch on bench',
  'reverse lunge to knee drive',
  'reverse nordic curl',
  'reverse sissy squat',
  'ring archer pull up',
  'ring bicep curl',
  'ring dip',
  'ring face pull',
  'ring fly',
  'ring muscle up',
  'ring push up',
  'ring row',
  'ring tricep extension',
  'rocking plank',
  'rope climb',
  'scapular pull up',
  'scapular push up',
  'scissor kick',
  'shrimp squat',
  'side lying hip abduction',
  'side lying windmill',
  'side plank dip',
  'side plank reach through',
  'single leg box squat',
  'single leg calf raise',
  'single leg glute bridge',
  'single leg hip thrust',
  'single leg soleus raise',
  'sissy squat',
  'sit up',
  'skin the cat',
  'slider body curl',
  'sliding leg curl',
  'slow mountain climber',
  'soleus raise',
  'spiderman push up',
  'sprawl',
  'staggered push up',
  'standing oblique crunch',
  'sumo stance calf raise',
  'tall plank shoulder tap',
  'tempo chin up',
  'tempo dip',
  'tempo pull up',
  'tempo push up',
  'thoracic spine rotation',
  'tibialis raise',
  'tibialis raise seated',
  'toe touch',
  'toes to bar',
  'towel pull up',
  'towel row',
  'tricep dip',
  'trx bicep curl',
  'trx chest press',
  'trx face pull',
  'trx fallout',
  'trx fly',
  'trx hamstring curl',
  'trx knee tuck',
  'trx lunge',
  'trx pike',
  'trx push up',
  'trx row',
  'trx single leg squat',
  'trx tricep extension',
  'trx w raise',
  'trx y raise',
  'v-up',
  'wall slide',
  'wall walk',
  'wide grip chin up',
  'wide grip pull up',
  'wide grip pull up behind neck',
  'wide grip push up',
  'windshield wiper',
  'world''s greatest stretch'
]::TEXT[]);

UPDATE public.exercises SET exercise_type = 'holds'
WHERE coach_id IS NULL AND lower(name) = ANY (ARRAY[
  '90/90 hip stretch',
  'butterfly stretch',
  'child''s pose',
  'couch stretch',
  'cross body shoulder stretch',
  'doorway chest stretch',
  'frog stretch',
  'hip flexor stretch',
  'pancake stretch',
  'pigeon stretch',
  'seated forward fold',
  'sleeper stretch',
  'standing hamstring stretch',
  'supine spinal twist',
  'wall lat stretch'
]::TEXT[]);
